#!/usr/bin/env python3
"""Pack assets/png/rom/*.png into c/assets_indexed.inc.

PRG32's cartridge builder compiles exactly one C source file (see
prg32/cartridge/build_cartridge.py), so every indexed sprite/tile asset this
cartridge uses has to live in a single translation unit. This script reuses
PRG32's own `tools/prg32_image_convert.py` packing functions (the same code
the `indexed`/`bitplanes` examples in PRG32's devicedemo cartridge rely on)
against each PNG in assets/png/rom/, and concatenates the results into one
generated file that c/game.c pulls in with #include.

Requires PRG32_REPO to point at a PRG32 checkout (same convention as
scripts/build.sh).
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ROM_DIR = ROOT / "assets" / "png" / "rom"
OUT_PATH = ROOT / "c" / "assets_indexed.inc"


def load_converter():
    prg32_repo = os.environ.get("PRG32_REPO", str(ROOT.parent / "PRG32"))
    tools_dir = Path(prg32_repo) / "tools"
    if not (tools_dir / "prg32_image_convert.py").exists():
        raise SystemExit(
            f"error: set PRG32_REPO to a PRG32 checkout (looked in {tools_dir})"
        )
    sys.path.insert(0, str(tools_dir))
    import prg32_image_convert as pic  # noqa: E402
    return pic


# (png filename, symbol, mode, colors, transparent_index, frame_w, frame_h)
# frame_w/frame_h crop the sheet into a row-major grid of sub-frames (cols =
# sheet_w // frame_w, rows = sheet_h // frame_h); None means "whole image is
# one frame". The ingredients sheet is a 4-kind x 4-anim grid, so its frame
# index is kind * 4 + anim -- exactly the indexing game.c uses.
ASSETS = [
    ("rom_professor_4frames_12x16.png", "art_professor", "indexed", 16, 0, 12, 16),
    ("rom_student_blue_4frames_12x16.png", "art_student_blue", "indexed", 16, 0, 12, 16),
    ("rom_student_magenta_4frames_12x16.png", "art_student_magenta", "indexed", 16, 0, 12, 16),
    ("rom_ingredients_4x4_28x12.png", "art_ingredients", "indexed", 16, 0, 28, 12),
    ("rom_tile_arch_20x26.png", "art_tile_arch", "bitplanes", 16, -1, None, None),
    ("rom_tile_stone_16x10.png", "art_tile_stone", "indexed", 16, -1, None, None),
    ("rom_tile_ladder_14x12.png", "art_tile_ladder", "indexed", 16, 0, None, None),
    ("rom_tile_plate_80x24.png", "art_tile_plate", "indexed", 16, 0, None, None),
    ("rom_title_emblem_56x48.png", "art_title_emblem", "indexed", 256, 0, None, None),
    ("rom_life_icon_8x8.png", "art_life_icon", "indexed", 16, 0, None, None),
]


def crop_frames(image, frame_w: int | None, frame_h: int | None):
    """Split a sheet into a row-major grid of sub-frames (or return it whole)."""
    if frame_w is None:
        return [image], image.width, image.height, 1
    cols = image.width // frame_w
    rows = image.height // frame_h
    frames = []
    for r in range(rows):
        for c in range(cols):
            box = (c * frame_w, r * frame_h, (c + 1) * frame_w, (r + 1) * frame_h)
            frames.append(image.crop(box))
    return frames, frame_w, frame_h, len(frames)


def convert_one(pic, png_path: Path, symbol: str, mode: str, colors: int,
                transparent_index: int, frame_w: int | None, frame_h: int | None) -> str:
    sheet = Image.open(png_path).convert("RGB")
    frames, width, height, frame_count = crop_frames(sheet, frame_w, frame_h)

    values: list[int] = []
    for frame in frames:
        values.extend(pic.rgb565(pixel) for pixel in frame.getdata())

    palette, indices = pic.exact_palette_indices(values, colors)
    bits_per_pixel = {2: 1, 4: 2, 8: 3, 16: 4, 256: 8}[colors]
    pixels_per_frame = width * height
    data: list[int] = []
    for start in range(0, len(indices), pixels_per_frame):
        frame_indices = indices[start:start + pixels_per_frame]
        if mode == "indexed":
            data.extend(pic.pack_indexed(frame_indices, bits_per_pixel))
        else:
            data.extend(pic.pack_bitplane_rows(frame_indices, width, height, bits_per_pixel))

    emit = pic.emit_compact_c
    text = emit(symbol, data, palette, width, height, len(frames), bits_per_pixel,
               transparent_index, planar=(mode == "bitplanes"))
    used_colors = len(palette)
    print(f"  {symbol:20s} {mode:9s} {colors:3d}c (used {used_colors:3d}) "
          f"{width}x{height}x{len(frames)}f -> {len(data)} bytes")
    return text


def main() -> None:
    pic = load_converter()
    print(f"packing indexed assets from {ROM_DIR}")
    chunks = [
        "/* Generated by assets/pack_indexed_assets.py -- do not edit by hand.\n"
        " * Included directly into c/game.c (PRG32 cartridges compile a single\n"
        " * translation unit, so every sprite asset has to live here). */\n",
        '#include "prg32.h"\n',
    ]
    for filename, symbol, mode, colors, transparent_index, frame_w, frame_h in ASSETS:
        png_path = ROM_DIR / filename
        if not png_path.exists():
            raise SystemExit(f"missing {png_path}; run generate_indexed_art.py first")
        text = convert_one(pic, png_path, symbol, mode, colors, transparent_index,
                           frame_w, frame_h)
        # Drop the per-file #include line; we already emitted one shared copy.
        lines = [ln for ln in text.splitlines() if not ln.startswith('#include "prg32.h"')]
        chunks.append("\n".join(lines) + "\n")

    OUT_PATH.write_text("\n".join(chunks), encoding="utf-8")
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
